### ISSUE TITLE
Should I make big cartouches (13379…7B, 42F) as big as 13258 etc?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/egyptian-hieroglyphs#11]
### Title 
I probably made these characters too small

### Font
NotoSansEgyptianHieroglyphs-Regular.otf

### Where the font came from, and when
Site: this repo, head of gh-pages
Date: 2024-01-24

### Font Version
2.001 (does it matter?)

### OS name and version
All OS

### Application name and version
All apps

### Issue
Probably made them too small, my bad. Suggest making them as big as 13258/5D

### Character data
U+13379 Egyptian hieroglyph V011a
U+1337A Egyptian hieroglyph V011b
U+1337B Egyptian hieroglyph V011c
U+1342F Egyptian hieroglyph V011d

### Screenshot
![image](https://github.com/notofonts/egyptian-hieroglyphs/assets/10164882/33daa42b-66be-4e11-8237-758bed8222ee)

**Comment by Mercury13** [comment]
@dwerning, need your help…

**Comment by dwerning** [comment]
@Mercury13 
Yes the cartush beginnings and endings should have the same height as full height signs, e.g.,
- 13261 𓉡 EGYPTIAN HIEROGLYPH O010

![grafik](https://github.com/notofonts/egyptian-hieroglyphs/assets/33833393/440fcad1-4cd5-42a9-9d0a-84d8e3675779)

**Comment by Mercury13** [comment]
Thx, wait for evening

**Comment by dwerning** [comment]
Height seems o.k. now. 

However, I wonder why FontForge displays it with the base line sifted to the bottom.

![grafik](https://github.com/notofonts/egyptian-hieroglyphs/assets/33833393/9a4bb5d3-4f89-4960-a9e6-62c8c27a6159)

![grafik](https://github.com/notofonts/egyptian-hieroglyphs/assets/33833393/832072eb-1523-44b5-9eb6-b75cd015c66a)

**Comment by dwerning** [comment]
@Mercury13 
Seems 43F (only?) is yet to small?!

![grafik](https://github.com/notofonts/egyptian-hieroglyphs/assets/33833393/26cf5d97-b364-47f2-942d-99e11f1f83ba)

**Comment by Mercury13** [comment]
@dwerning #15 accepted → set OK
