### ISSUE TITLE
Should we increase 25CC to the size of an average hiero?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/egyptian-hieroglyphs#12]
### Title 
Probably need to enlarge 25CC to the size of an average hieroglyph

### Font
NotoSansEgyptianHieroglyphs-Regular.otf

### Where the font came from, and when
No matter, actually unchanged

### Font Version
No matter, actually unchanged

### OS name and version
All OS

### Application name and version
All apps

### Issue
We’ll add shading signs <s>soon</s> someday. And, to showcase them, increase size of 25CC to the size of average hieroglyph.

### Character data
U+25CC dotted circle

### Screenshot
![image](https://github.com/notofonts/egyptian-hieroglyphs/assets/10164882/f8014e2b-523f-4b10-b1f0-cbbc7cee6b03)

**Comment by simoncozens** [comment]
Makes sense, yes.
