### ISSUE TITLE
A60 = 13045: replace dashed line with dots?

### ISSUE THREAD

**Issue by Mercury13** [notofonts/egyptian-hieroglyphs#13]
### Title
A60 = 13045: we probably need to replace dashed line with dots

### Font 
NotoSansEgyptianHieroglyphs-Regular.otf

### Where the font came from, and when
No matter, glyph did not change

### Font Version
No matter, glyph did not change

### OS name and version
All OS

### Application name and version
All apps

### Issue
If he’s “man sowing seeds” — probably we should draw dots rather than dashes.

### Character data
U+13045 Egyptian hieroglyph A060

### Screenshot
![image](https://github.com/notofonts/egyptian-hieroglyphs/assets/10164882/61d6ef39-944c-4813-ad0f-9ca277331c07)

**Comment by Mercury13** [comment]
@dwerning, need help…

**Comment by dwerning** [comment]
@Mercury13 
Yes, dots would be more adequate.

**Comment by Mercury13** [comment]
Thx, wait for evening

**Comment by Mercury13** [comment]
@dwerning Check…

**Comment by Mercury13** [comment]
#15 will fix it
