### ISSUE TITLE
Redraw Egyptian hieroglyphs according to 2021 changes

### ISSUE THREAD

**Issue by Mercury13** [notofonts/egyptian-hieroglyphs#3]
### Title 
Unicode 14 redrew several Egyptian hieroglyphs, and you should check them

### Font
NotoSansEgyptianHieroglyphs-Regular.otf

### Where the font came from, and when
Site: this repo
Date: 2021-12-18

### Font Version
2.000

### OS name and version
All OS

### Application name and version
All apps

### Issue
2009 images were correct but poor.
2016 images were redrawn by professional designer, but historically worse.
2021 images were corrected by Egyptologists

### Character data
1300A bend knee more
13017 not so bent man
13032 remove beard
13034 remove beard
13035 OK (enlarged beard)
13037 OK (enlarged beard)
13038 shorter beard
1303A change hairstyle, shorten beard
1303B shorten beard
1303C shorten beard
1303D so-so (you may shorten beard)
1303E so-so (you may enlarge beard)
1304E change hand position
1304F OK (changed hands position)
13055 seemingly OK (I don’t see what’s the trouble)
13057 remove beard, turn man to woman
13068 add beard
1309A shovel with bread, not skewer with meat
130D2 horns should point outwards
130D5 ankh on cow’s neck
130F6 I don’t see the point, probably something else on the neck instead of ankh
130FE horns should point outwards
13192 OK (snake should have ears)
1325F rectangle on lower-right
13267 no teeth on the right
1326A snakes should point to different sides, three to the left and four to the right
13281 borders of the comb should reach the top
13297 probably lotus? seeds should be placed chaotically
1329E papyrus on boat’s stern
132B4 rectangular receptacles, not round breads
132C1 another shape of horizontal thing
132E6 OK (something else is hanging, and you are right)
13304 OK (another shape of tool)
1331F lower prong should not be triangular
13378 OK (all fonts did right despite 2016 drawing)
13379, 7A, 7B higher
1337D seemingly OK
1337E OK
133F3 shorter
133FA..403 OK? reference images are hollow now, but simple stick probably isn’t a mistake.
1340D OK (horizontal hatch, not diagonal)
13417 cylindrical tool, not sausage-like
1342B OK (all fonts did right)

**Comment by dwerning** [comment]
Please find an overview of signs to be corrected in the PDF here: 
https://osf.io/9haqz

13017	Not bend that low
1302D	Make beard longer, curved at the end
13032	Remove beard
13033	Remove uraeus at the front of the crown
13034	Remove beard
13038	Make beard shorter, edged end, as in v14
1303A	Make beard shorter, pointed end
1303B	Make beard shorter, edged end, as in v14
1303C	Make beard shorter, edged end, as in v14
1303D	Make beard shorter, edged end, as in v14
1303E	Make beard longer, curved at the end
1303F	Make beard longer, curved at the end
13040	Make beard longer, curved at the end
1304E	Turn upper hand, palm outwards
13057	(Queen erroneously as king in v9); (a) Remove beard; (b) Redesign hair and breast as in U+13050 𓁐
13068	(a) Knees like in U+13000 𓀀; (b) Redesign headdress; (c) Long bread, curved at the end
130D2	Horns curved, pointing outwards
130D5	Add 𓋹 around the neck
130FE	Horns mor like in (revides) U+130D2
1325F	Move rectangular compartment to the right
13267	Remove ticks at the right
1326A	Mirror four rightmost uraei 
13297	Sand pattern like in v5.2
1329E	Redesign read part of ship
132B4	Rectangual things on the table
132C1	Substitute 𓈋 by simple platform
1331F	Substitute triagle in the lower part by stroke
13378	(Good shape; not to be confused with the shape/height in U+1317A)
13379	Make full height; not like in U+13378
1337A	Make full height; not like in U+13378
1337B	Make full height; not like in U+13378
133D4	(Good shape; cf. U+133F3 below)
133F3	Make recognizably less wide than U+133D4
13417	Rectangular middle
1342B	Fill knob (not to be confused with U+133DD)

**Comment by Mercury13** [comment]
Does it compile? I can start fixing ≈2 hieros a week, but first ensure that it compiles, we did not compile for a year.

**Comment by Mercury13** [comment]
And do we have better sources than *.glif? For example, *.svg?

**Comment by Mercury13** [comment]
I won’t touch 1300A, as there are controversies here whether it should be a fist or palm to other side.

**Comment by Mercury13** [comment]
Is it OK?
![u13015_NotoSansEgyptianHieroglyphs-Regular](https://github.com/notofonts/egyptian-hieroglyphs/assets/10164882/e64e4405-241e-44c9-85af-04810853fe0e)

**Comment by dwerning** [comment]
> I won’t touch 1300A, as there are controversies here whether it should be a fist or palm to other side.

It should be alms as best visible in the "JSesh font" example. Its a man 'drumming' on his chest alternately with his left and right **fist**.

**Comment by dwerning** [comment]
> And do we have better sources than *.glif? For example, *.svg?

There are SVGs in the JSesh package (https://github.com/rosmord/jsesh/tree/master/jseshGlyphs/src/main/resources/jseshGlyphs; in addition, extented and individual sets: https://jsesh.qenherkhopeshef.org/glyphshttps://jsesh.qenherkhopeshef.org/glyphs). However, the glyphs there have a style very different from the Glyph/WinGlyph/Hieroglyphica style that the Unicode set is based on. Cf., e.g., the design of the arms. Therefore, expecially for humans/gods, they are not always good models.

**Comment by Mercury13** [comment]
@dwerning Why I’m asking? All fonts have zero-width outlines → lines containing width and centerline are lost. If we don’t have → I see, they are done rather sloppily, I won’t introduce a great mess. I’ve found some thesis about what is **hnw**; if fists then fists.

**Comment by Mercury13** [comment]
@dwerning At least I need to check how fists are drawn in other fonts and glyphs.

**Comment by dwerning** [comment]
> Is it OK? 
Looks good to me. Thank you. Feel free to contact me directly by email for quick individual questions or evaluation purposes.

**Comment by Mercury13** [comment]
@dwerning I’ll make three or four hieros, and start a pilot PR. I don’t even know whether this font compiles!

**Comment by dwerning** [comment]
> > I won’t touch 1300A, as there are controversies here whether it should be a fist or palm to other side.
> 
> It should be alms as best visible in the "JSesh font" example. Its a man 'drumming' on his chest alternately with his left and right **fist**.

See here: https://thebanmappingproject.com/images/10482jpg

**Comment by Mercury13** [comment]
About better sources — I mean, *.glif weren’t intended for direct editing. They were made from SVGs.

**Comment by Mercury13** [comment]
![image](https://github.com/notofonts/egyptian-hieroglyphs/assets/10164882/9f7985cc-fecf-4be8-81b7-f86a16853960)
00A moved feet, but did not change to fists for now. It’ll be a bit hard, but I’ll do. That’s why I posted a screen rather than SVG.

**Comment by Mercury13** [comment]
@dwerning, should 017 be slightly edited 018 (like in U14, NewGardiner), or bend it a little bit lower (like in Segoe)?

**Comment by dwerning** [comment]
> @dwerning, should 017 be slightly edited 018 (like in U14, NewGardiner), or bend it a little bit lower (like in Segoe)?

u13017 (old man) should be **bend** like in Segoe (but not so much as in Unicode v9 (= Hieroglyphica)), clearly distinguishable from u13018 (noble man).

**Comment by dwerning** [comment]
**Review**
- 017: should be **identical in posture to 018** except for lower end of stick (sorry that I have not seen this earlier)
- 02D: (**does not show** in my FontForge!?!)
- 033: fine now, beard correct (longish/not rounded => king's beard)
- 034: fine now
- 038: fine now, beard correct (short/edged/not rounded => noble man's beard)
- 039: fine now
- 03A: beard fine (short/pointed => foreigner's beard; forgot to mention: **headdress needs to be changed** (should not be an Egyptian god's headdress; see: https://osf.io/9haqz)
- 03B: fine now
- 03C: fine now
- 03D: fine now
- 03E: fine now
- 03F: fine now
- 040: fine now
- 04E: fine now
- 057: fine now
- 075: fine now

Thank you for your work on this!

**Comment by simoncozens** [comment]
Thanks to @Mercury13 for design and @dwerning for review. I'd be very happy to merge the PR once the two/three remaining issues are addressed.

**Comment by Mercury13** [comment]
@simoncozens Possibly did all men and gods; I’ll get a review, and you merge and check for compilation. And I’ll have a little rest.

**Comment by Mercury13** [comment]
Part one, men and gods, probably done.

**Comment by simoncozens** [comment]
Brilliant, I'm going to merge it. Thank you so much.

**Comment by Mercury13** [comment]
@dwerning Part one accepted today, I’ll check technical correctness.
Concerning 130FB, 0FC: 1) does tail position matter? 2) Does knot shape matter?
And could you find some original images of hamadryas?
Concerning cows/bulls: what about horns? When should they point inside and when outside?

**Comment by dwerning** [comment]
> Concerning 130FB, 0FC: 1) does tail position matter? 2) Does knot shape matter?
> And could you find some original images of hamadryas?
> Concerning cows/bulls: what about horns? When should they point inside and when outside?

- 0FB/0FC: it is important that is is clearly a (hamadryas) babbon, which is not clearly the case in the Noto shape. As to tail and form: it should be the form as in Univode v9--v15. The extension in forthcoming v16 will add the shape of v15 but with tail upwards as a variation. So the shape of 0FB/C must have the tail on the ground.

- Bovide horns: Turning inwards *only* for the 'aggressive bull', i.e. 0D3 and 100, or the slaughtered bull (forthcoming).
All the others with horns pointing outwards, cf. v16 candidate https://www.unicode.org/L2/L2023/23181-n5240-hieroglyphs.pdf. (BTW: Horns in 0FE just like in 0D2 would be nice.)
As for 226--22C: tricky. Leave those they are.

**Comment by Mercury13** [comment]
@dwerning Is 0F7 (E32) baboon of monkey? Should I change it?

**Comment by Mercury13** [comment]
@dwerning I found one shortcoming in 0F9/0FA (E34(a), hare/low hare). Low hare is just a shrunken hare. Should I improve them somehow?

**Comment by dwerning** [comment]
> Is 0F7 (E32) baboon of monkey? Should I change it?

0F7/8 should stay the way it is. 
0FB/C is special since it is also used for god Thot in which case it must be the very specific form of the baboon as in v9-v15.

**Comment by dwerning** [comment]
> I found one shortcoming in 0F9/0FA (E34(a), hare/low hare). Low hare is just a shrunken hare. Should I improve them somehow?

This was a shortcoming/mistake/misunderstanding in the proposal for v5.2. (Same for 168/9, 16A/B, 39F/A0, 3B1/2.) The shrunken variants are going to be set to a kind of usage blacklist with v16. So just leave them as they are.

**Comment by Mercury13** [comment]
Checking what is already done
✅ = merged, 🟡 = checked, 🔴 = unchecked, ❎ OK somehow ❔ still not done ➰ popped out amid work


✅ 1300A Turn upper hand, palm outwards Both hands should be fists, cf. v5.2
✅ 13015 Lower upper arm a little
✅ 13017 Not bend that low
✅ 1302D Make beard longer, curved at the end
✅➰ 1302E
✅ 13032 Remove beard
✅ 13033 Remove uraeus at the front of the crown
✅ 13034 Remove beard
✅➰ 13035, 036, 037
✅ 13038 Make beard shorter, edged end, as in v14
✅ 13039 Remove beard
✅ 1303A Make beard shorter, pointed end
✅ 1303B Make beard shorter, edged end, as in v14
✅ 1303C Make beard shorter, edged end, as in v14
✅ 1303D Make beard shorter, edged end, as in v14
✅ 1303E Make beard longer, curved at the end
✅ 1303F Make beard longer, curved at the end
✅ 13040 Make beard longer, curved at the end
✅ 1304E Turn upper hand, palm outwards
✅ 13057 (Queen erroneously as king in v9); (a) Remove beard; (b) Redesign hair and breast as in U+13050 𓁐
✅➰ 1305A 064
✅ 13068 (a) Knees like in U+13000 𓀀; (b) Redesign headdress; (c) Long bread, curved at the end
✅➰ 13069…06D, 06F
✅ 13075 (a) Remove beard; (b) correct crown
✅➰ 13076
❎ 1309A Substitute mace for sword(?) (Good shape, v15 again like v9)
🟡 130D2 Horns curved, pointing outwards
🟡 130D5 Add 𓋹 around the neck
🔴 130FB Redesign according to shape in v5.2
❔ 130FC Redesign ape according U+130FB
🟡 130FD (Female cow) Redesing horn, longer/wirder than in U+130D2; remove penis under belly, add udder
🟡 130FE Horns mor like in (revides) U+130D2
🟡 13108 Redesign according to U+130FE
🟡 13163 Redesign shape
✅➰ 1317D
🟡 1325F Move rectangular compartment to the right
🟡 13267 Remove ticks at the right
🟡 1326A Mirror four rightmost uraei
❎ 13281 Leave as it is (insignificant)
🟡 13297 Sand pattern like in v5.2
🔴 1329E Redesign rear part of ship
🔴 1329F Redesign stern
🟡 132B4 Rectangual things on the table
🔴 132C1 Substitute 𓈋 by simple platform
🔴 1331F Substitute triagle in the lower part by stroke
❎ 13378 (Good shape; not to be confused with the shape/height in U+1317A)
🔴 13379 Make full height; not like in U+13378
❔ 1337A Make full height; not like in U+13378
❔ 1337B Make full height; not like in U+13378
❎ 133D4 (Good shape; cf. U+133F3 below)
🔴 133F3 Make recognizably less wide than U+133D4
🔴 13417 Rectangular middle
🔴 13420 Delete extra line
🔴 1342B Fill knob (not to be confused with U+133DD)

U15:
❔ 1342F other cartouche
❔ 13441 hiero space wide
❔ 13442 hiero space narrow
❔ 13443 hash big
❔ 13444 hash small
❔ 13445 hash tall
❔ 13446 hash wide
And maybe draw some images for formats until we fully support them.

**Comment by Mercury13** [comment]
@simoncozens While our reviewer is out here (seriously ill), maybe I’ll make a side-branch to merge what’s has been reviewed?

**Comment by simoncozens** [comment]
I'm happy to merge a partial PR, but it looks like he's back in action!

**Comment by Mercury13** [comment]
I was really glad, and even answered to Daniel, but could not redraw even boats.

**Comment by Mercury13** [comment]
I also need to retrieve some stats about hieros’ widths to make 443/44. Needs a little programming → cannot either.

**Comment by Mercury13** [comment]
Again “probably-done”. If my work is approved, I check once again, you merge and close this issue.

**Comment by Mercury13** [comment]
@simoncozens Closing this issue, everything mentioned here (except hashes and hiero spaces) are done?

**Comment by dwerning** [comment]
@simoncozens When, approximately, will the corrected version of _Noto Sans Egyptian Hieroglyphs_ be officially online on https://fonts.google.com/noto/specimen/Noto+Sans+Egyptian+Hieroglyphs?noto.script=Egyp, or is there already another place from which one can download it?

**Comment by simoncozens** [comment]
For the first question, I'll put it on the list for the end of this quarter. I was hoping to create a WASM version supporting the layout formatting controls, but I think that's less likely to happen this quarter so I'll just release what we have.

For the second question, you can get development versions from https://notofonts.github.io/egyptian-hieroglyphs/
