### ISSUE TITLE
U+130B8, U+130B9 and U+130BA missing

### ISSUE THREAD

**Issue by jasperhabicht** [notofonts/egyptian-hieroglyphs#4]
The Noto fonts where designed to prevent displaying "tofu" (the small rectangles that are displayed if the computer has not font at hand to display a specific glyph). The font Noto Sans Egyptian Hieroglyphs still seems to be missing three glyphs, namely U+130B8, U+130B9 and U+130BA.

The font Noto Sans Egyptian Hieroglyphs may be used in a scientific context for transcribing ancient inscriptions that display the glyphs that are assigned to these three codepoints. Despite the fact that these three glyphs that display a phallus may be considered offensive in certain contexts, in oder to be able to properly render transcriptions of such inscriptions, I strongly advocate the inclusion of these three glyphs in the font.

In case that including these three glyphs is a problem due their perceived offensive nature, an alternative rendering of these three glyphs should be considered or at least a placeholder glyph, so that the user of the font won't be offered "tofu" but a sensible alternative representation of these three glyphs.

**Comment by Mercury13** [comment]
When was it deleted?
![изображение](https://user-images.githubusercontent.com/10164882/181313309-59594555-686c-47f9-b7d7-a74fe0f0ecec.png)

**Comment by Mercury13** [comment]
Dev builds have too, but M$ Segoe DOES NOT have. Maybe you checked the wrong font?

**Comment by jasperhabicht** [comment]
I downloaded the font again from Google Fonts and opened it with FontForge. I can confirm that the glyphs are in there. Maybe really the wrong font was selected.

**Comment by dwerning** [comment]
For MS's _Segoe UI Historic_, there is a mechanism that these glyphs are only displayed iff standing directly next to other hieroglyphs. Next to non-hieroglyphic chars only a rectangle appears. In the case of _Noto Sans EgyptianHiero_ all three signs should appear anywhere.
