### ISSUE TITLE
Add seven new hieroglyphs: reversed cartouche end, 2D destruction signs, 2D blanks

### ISSUE THREAD

**Issue by dwerning** [notofonts/egyptian-hieroglyphs#5]
### Title
Add seven new hieroglyphs to _Noto Sans Egyptian Hieroglyphs_
### Font
NotoSansEgyptianHieroglyphs-Regular.ttf
### Font Version
Version 2.0
### Feature request
In Unicode 15.0, seven (six plus one) new (partially important) hieroglyphs are added.  Please consider to add those to Noto Sans Egyptian Hieroglyphs font.
- **Reversed cartouche end**
U+1342F, https://www.unicode.org/charts/PDF/Unicode-15.0/U150-13000.pdf
![grafik](https://user-images.githubusercontent.com/33833393/190088339-7bbf4bab-1c52-4a6c-901f-4a786f3439c4.png), effectively mirrored version of ![grafik](https://user-images.githubusercontent.com/33833393/190088448-2e7af77d-8c13-423a-921f-16fb3681a08e.png)
- Four 2-dimensional **atomic destruction signs** (behaving like normal hieroglyphs)
U+13443-13446 https://www.unicode.org/charts/PDF/Unicode-15.0/U150-13430.pdf
Please implement as as hashed blocks as usual in Egyptology:
![grafik](https://user-images.githubusercontent.com/33833393/190092239-ec92908a-68fa-4755-8eba-0c8b08d43475.png)
- Two 2-dimensional **atomic blanks** (behaving like normal hieroglyphs)
U+13441/13442 https://www.unicode.org/charts/PDF/Unicode-15.0/U150-13430.pdf
  - U+13441: quadratic blank with 100% of a full sign's height
![grafik](https://user-images.githubusercontent.com/33833393/190091589-54425ef0-c99a-40b1-af6a-715f0f77f4f2.png)
  - U+13442: quadratic(!) blank with 50% of a full sign's height (don't be confused: despite the name "half blanks", it is actually a quarter blank in two dimentions)
![grafik](https://user-images.githubusercontent.com/33833393/190091036-89e76a97-58a0-44e4-9ff7-26a7848f3e2d.png)

Examples collected in context of the Unicode proposal: D.A. Werning, _Demand for an Addition of Further Hieroglyphic Control Characters and Special Signs to the Unicode Set: Sondage of Usages in Different Scholarly Publications and the TLA Text Database_, https://osf.io/p539b

**Comment by Mercury13** [comment]
So, what’s remaining?
❔ 13441 hiero space wide
❔ 13442 hiero space narrow
❔ 13443 hash big
❔ 13444 hash small
❔ 13445 hash tall
❔ 13446 hash wide

**Comment by Mercury13** [comment]
@dwerning As the sources are openable in FontForge, there’s a thing. I draw some hashes, and you confirm that they are OK in your pitches.

**Comment by dwerning** [comment]
Great, waiting for it.

**Comment by Mercury13** [comment]
@dwerning #15 accepted → set OK

**Comment by Mercury13** [comment]
@simoncozens Please close, fixed with #15

**Comment by Mercury13** [comment]
Please close, fixed with #15
